### ISSUE TITLE
Generalizing callback monad and redesigning API

### ISSUE THREAD

**Issue by mtesseract** [mtesseract/nakadi-client#56]
## This is the first part of a major API redesign.

Note that the current API has never been declared stable.

I suggest to work on this for a future 0.5.0.0 release.
@etorreborre @vitold @amrhassan 

### What is wrong with the current API?

Several things are not perfect, but let's focus on one aspect for now. Namely, all callbacks registered by the user in the Nakadi configuration are to be run in the `IO` monad. This is not a strict limitation, but an inconvenience, as the user might be using some more complicated monad stack on top of `IO` for an application. Nakadi requiring callbacks in the `IO` monad therefore means that the user might has to do some type conversion, e.g. by unwrapping the custom monad stack, before providing the callbacks to nakadi-client.

### What would be nicer?

It would be nicer if the user could decide for some custom "base monad" in which the callbacks are to be run. As these callbacks are stored in the Nakadi configuration value `Config`, this value needs to be parameterized by this `base` monad. [Note, there is some conflict in terminology here. What is often called 'base monad' in Haskell (see e.g. the `transformers-base` package), is a specific monad among `STM`, `IO`, `Maybe`, etc..  Something like

    type App a = ReaderT IO a

would not be a 'base monad'. This is different in the usage of the word within nakadi-client. A base monad here means 'the custom monad transformer stack for your application'. Thus, `ReaderT IO` could be a base monad, if that is what the callbacks produce.

As mentioned previously, the `Config` type would now be parameterized by some base monad `b`. So, a nakadi-client function could look as follows:

```
eventTypesList :: SomeConstraints b => Config' b -> b [EventType]
```

But this would be a bad API, as this would mean that the only monad in which nakadi-client calls could be executed would be the application's base monad `b`. For example, consuming events, requires a `MonadResource` constraint on the monad to run in. More generally speaking, the user should always be free to locally run in some other monad stack — as long as it has the same base monad at the bottom. Otherwise we couldn't call the user's callbacks without unlifting them.

To sumarize the above: We need at least two monads `b` and `m` and a 'sub-monad' relationship between them. Thus, we end up with something like this: 
```
eventTypesList :: (MonadSub b m, ...) => Config' b -> m [EventType]
```

In the above, we actually need some more type class constraints on `b` and `m`, namely `MonadIO m`, `MonadIO b`, `MonadCatch m` and `MonadMask b`. 

Currently, the nakadi-client package exposes basically two sets of API calls:

- Those, which require the Nakadi configuration to be given as first argument and

- those, which expect the Nakadi configuration to be implicitely available (currently, these are suffixed with 'R').

The current mechanism by which the implicit configuration was made available consisted of two parts:

- the `HasNakadiConfig` type class is defined and provided by nakadi-client

- the user implements this type class for some reader monad type in which the nakadi-client '*R' functions are used.

Sadly this way of doing things no longer works when the configuration is parameterized by the base monad, as this means that the `b` type cannot be uniquely inferred anymore: Given some monad stack involving several layers, there are many potential ways to slice this monad stack into a base monad and the rest. One would have to provide a `Proxy b` argument or something similar ugly to make type checker happy — clearly not an option.

### Approach

So, how we can we make it work instead? I have tried to go with the following solution:

- Define a modified and specialized `ReaderT` monad transformer named `NakadiT`:

```
newtype NakadiT b m a = NakadiT { _runNakadiT :: Config' b -> m a }
```

- Define the type class `MonadNakadiEnv` which defines the API for working with implicitely stored Nakadi configurations:

```
class SomeConstraints b m => MonadNakadiEnv b m | m -> b where
    nakadiAsk :: m (Config' b)
    nakadiReader :: (Config' b -> a) -> m a
```

- Implement `MonadNakadiEnv` for `NakadiT`

- Implement `MonadNakadiEnv` for monad transformers on top of `NakadiT`, in particular `ReaderT` and `ResourceT`. 

- Let the API for the '*R' calls require this type class constraint. For example:

```
eventTypesListR :: MonadNakadiEnv b m => m [EventType]
```

This looks like a rather convenient API. In particular, it does not limit the user to some specific monad stack. Instead, basically any super monad of `b` implementing `MonadNakadiEnv` can be used now.

Why using something like `NakadiT` instead of simply using `ReaderT`?

Because in applications it is common to have a `ReaderT` somewhere in the monad stack. Having two `ReaderT`s in there makes it difficult to use a mtl-style interface like `MonadReader`. Using something distinct like `NakadiT` keeps us totally seperated from `ReaderT`s contained in the application's custom monad stack.

This is what this branch (*parameterize-monad*) is about:

- Generalizing `Config` to `Config b`
- Implementing `MonadSub`, `MonadNakadi` and `MonadNakadiEnv`
- Replacing the `HasNakadiConfig` mechanism with `MonadNakadiEnv`

**Comment by etorreborre** [comment]
From a distance I think it makes sense. I was also a bit annoyed by the functions in Config being in IO.
